apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ping-pong-cpu-usage
  namespace: project
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 2m
    interval: 30s
    count: 3
    successCondition: result < 0.0000001
    failureLimit: 1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(
            rate(container_cpu_usage_seconds_total{
              namespace="project",
              container!=""
            }[1m])
          )